jht3820/luna-agile

LICENSE
=> LICENSE change

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/adm/adm2000/adm2000/adm2000_SQL_cubrid.xml, luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/adm/adm7000/adm7000/adm7000_SQL_cubrid.xml
was동작시 문제 발생할 수 있는 쿼리 내부 불필요 주석 제거
=> 쿼리문 내부 불필요 주석 제거

luna-agile/src/main/webapp/js/axisj/dist/ax5/ax5grid.js
사용자 관리 그리드의 차단유무  컬럼 더블클릭 후 클릭 할경우 차단유무 select box가 열리자마자 닫히는 문제 수정
=> 사용자 관리 그리드의 차단유무 컬럼 클릭 이상 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj2000/prj2000/prj2000.jsp
IE에서 업무역할 관리 가로 전체체크 동작이상 문제 수정
=> IE에서 업무역할 관리 가로 전체체크 동작이상 문제 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm1000/adm1000/adm1000.jsp
IE에서 메뉴 및 권한관리 > 권한관리의 전체체크 이상 수정
- 권한관리에서 가로 전체체크 체크박스 클릭이상 수정
=> IE에서 메뉴 및 권한관리 > 권한관리의 전체체크 이상 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/arm/arm1000/arm1000/arm1000.jsp
쪽지 읽음 화면 <script> 태그 치환 추가 및 쪽지 내용 표시될 div를 textarea로 변경
(쪽지 내용에 입력된 태그가 동작하지 않도록 처리)
=> fix : 쪽지 화면 <script> 태그 치환처리 추가

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/top/aside.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/top/header.jsp
- 좌측 전체 요구사항 클릭 시 이동되는 메뉴 변경, 조직명 표시 수정
- 소메뉴가 없는 중메뉴 표시되지 않도록 수정
=> chore, fix : aside, header 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm2000/adm2000/adm2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm5000/adm5000/adm5000.jsp
- 사용자 관리 화면 Guide Box 추가 , 사용자 수정 팝업 사이즈 변경
- 로그인 이력 로그 그리드 컬럼 사이즈 변경, 기본 조회기간 추가
=> feat : 사용자 관리, 로그인 이력 로그

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm7000/adm7000/adm7000.jsp, luna-agile/src/main/webapp/css/oslops/dept.css
=> refactor : 조직관리 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/chk/chk1000/chk1000/chk1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/chk/chk1000/chk1100/chk1100.jsp
=> style : 결재 요청/승인 그리드 컬럼 사이즈 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/cmm/cmm4000/cmm4000/cmm4000.jsp
- 비밀번호 만료 사용자 로그인시 비밀번호 변경할 수 있는 팝업 추가
=> feat : 비밀번호 만료시 새로운 비밀번호 설정하는 팝업 추가

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dpl/dpl2000/dpl2000/dpl2000.jsp
=> refactor : 배포계획 요구사항 배정 개선

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1101.jsp
=> chore : ztree 전체펼침 개선, 그리드 컬럼사이즈 조정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1102.jsp
=> feat : 프로세스 설정 로직 개선, 작업흐름 항목 추가

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/cmm/cmm4000/cmm4000/cmm4000_SQL_cubrid.xml
=> fix : 로그인 후 메뉴조회 쿼리 수정

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/dpl/dpl2000/dpl2100/dpl2100_SQL_cubrid.xml
=> fix : 배포 결재 요청 쿼리수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh1000/dsh1000/dsh1000.jsp
=> fix : 운영대시보드 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj2000/prj2100/prj2100.jsp
=> fix : 프로젝트 사용자 배정 XSS 문제 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj3000/prj3000/prj3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj3000/prj3100/prj3100.jsp
=> chore : 개발문서 양식 설정, 개발문서 관리 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4000/req4000.jsp
=> style : 요구사항 분류 기준관리 메뉴 기능 안내문 변경

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4100/req4101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1000/stm1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1100/stm1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1200/stm1200.jsp
style : API 등록, 배정, 전체현황 그리드 컬럼 사이즈 변경
=> feat : 요구사항 등록 입력값 유효성 변경, 직급/직책 입력 항목 추가

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2000/stm2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2200/stm2200.jsp
=> style : 그리드 컬럼 사이즈 변경

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4100/req4101.jsp
=> fix : 요구사항 등록 - 요청자명 직접입력 시 유효성 변경

luna-agile/src/main/webapp/css/menu/aside.css, luna-agile/src/main/webapp/css/menu/header.css, luna-agile/src/main/webapp/css/oslops/dpl.css, luna-agile/src/main/webapp/css/oslops/dsh.css, luna-agile/src/main/webapp/css/oslops/flw.css, luna-agile/src/main/webapp/css/oslops/req.css
=> style : CSS Style 변경

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm2000/adm2000/adm2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm6000/adm6000/adm6000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh1000/dsh1000/dsh1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req1000/req1000/req1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1100/stm1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm3000/stm3100/stm3100.jsp
=> style : 그리드 컬럼 사이즈 조정

luna-agile/src/main/java/kr/opensoftlab/oslops/cmm/cmm9000/cmm9000/web/Cmm9000Controller.java
=> feat : 모듈 추가

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/req/req4000/req4100/req4100_SQL_cubrid.xml
=> fix : 대시보드 작업흐름의 전체/담당 요구사항 나오지 않는 오류 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prs/prs3000/prs3000/prs3002.jsp
- 메인프로젝트 input 부분  프로젝트명이 빈값으로 들어가는 부분 수정
=> fix : 개인정보 수정에서 프로젝트 선택 팝업 오류 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1102.jsp
fix : 프로젝트 그룹 수정 후 프로젝트 추가 시 그룹일자 오류 수정
=> fix : 프로젝트 그룹 수정 후 프로젝트 추가 시 그룹일자 오류 수정

luna-agile/src/main/java/egovframework/com/cmm/util/EgovUrlRewriteFilter.java, luna-agile/src/main/java/egovframework/com/cmm/web/EgovBindingInitializer.java, luna-agile/src/main/java/egovframework/com/cmm/web/EgovComIndexController.java, luna-agile/src/main/java/kr/opensoftlab/oslops/adm/adm1000/adm1000/web/Adm1000Controller.java, luna-agile/src/main/java/kr/opensoftlab/oslops/cmm/cmm4000/cmm4000/web/Cmm4000Controller.java, luna-agile/src/main/java/kr/opensoftlab/oslops/com/vo/PageVO.java, luna-agile/src/main/java/kr/opensoftlab/oslops/prj/prj2000/prj2000/web/Prj2000Controller.java, luna-agile/src/main/webapp/WEB-INF/config/egovframework/springmvc/dispatcher-servlet.xml
=> fix : PMD 소스 수정(사용자명 url 인코딩)

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/adm/adm2000/adm2000/adm2002.jsp
feat : 사용자 일괄 등록 시 이메일 중복체크 기능 추가
=> feat : 사용자 일괄 등록 시 이메일 중복체크 기능 추가

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh1000/dsh1000/dsh1000.jsp
=> chore : 공지사항 그리드 No 제거, 순번 추가

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1100/stm1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/top/header.jsp
=> style : 그리드 사이즈 변경 및 헤더 로고 변경

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1000/prj1000.jsp
=> chore : 프로젝트명 변경, 트리초기화 중복 제거

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1102.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/prj/prj2000/prj2000/prj2000.jsp
=> style : 프로젝트 명 변경에 따른 서식 변경

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/adm/adm7000/adm7000/adm7000_SQL_cubrid.xml
=> chore : 쿼리 내부 주석제거

luna-agile/src/main/java/kr/opensoftlab/oslops/cmm/cmm1000/cmm1200/web/Cmm1200Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/cmm/cmm1000/cmm1200/cmm1200.jsp
feat : 조직 선택 공통 팝업 동적 ztree 적용
=> feat : 조직 선택 공통 팝업 동적 ztree 적용

luna-agile/src/main/webapp/css/oslops/dsh.css
=> style : 대시보드 간격 조절

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh3000/dsh3000/dsh3000.jsp
=> style : 대시보드 서식 변경

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dpl/dpl2000/dpl2100/dpl2100.jsp
feat : 사용자 요구사항 소요등록. 데이터 더블클릭 시 요구사항 상세화면 출력 (접수대기, 반려인경우 기존 상세화면 사용)
=> feat : 사용자 요구사항 소요등록. 데이터 더블클릭 시 요구사항 상세화면 출력 (접수대기, 반려인경우 기존 상세화면 사용)

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh1000/dsh1000/dsh1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh2000/dsh2000/dsh2000.jsp
=> chore : 불필요한 주석 제거, 쪽지 기능 제거

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req1000/req1000/req1000.jsp
feat : 사용자 요구사항 소요등록(데이터 버블클릭 시 요구사항 상세화면 출력-접수대기, 반려인 경우 기존 상세화면 사용)
=> feat : 사용자 요구사항 소요등록(데이터 버블클릭 시 요구사항 상세화면 출력-접수대기, 반려인 경우 기존 상세화면 사용)

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req2000/req2000/req2000.jsp
=> chore : 불필요한 주석 제거

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4100/req4106.jsp
refactor : 요구사항 상세화면 팝업 수정(팝업 스타일 추가 및 변경, 코드 간략화, 변수추가)
=> refactor : 요구사항 상세화면 팝업 수정(팝업 스타일 추가 및 변경, 코드 간략화, 변수추가)

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4100/req4100.jsp
=> chore : 불필요한 주석 정리

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4100/req4105.jsp
refactor : 요구사항 심시 저장 함수 정리 및 메세지 출력 수정
=> refactor : 요구사항 심시 저장 함수 정리 및 메세지 출력 수정

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4200/req4200.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4800/req4800.jsp
feat : 불필요한 주석 제거, 사용자 요구사항 소요등록 상세화면
=> feat : 불필요한 주석 제거, 사용자 요구사항 소요등록 상세화면

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/req/req4000/req4100/req4100_SQL_cubrid.xml
chore : 요구사항 리비전 목록 조회 쿼리 정렬 컬럼 변경
=> chore : 요구사항 리비전 목록 조회 쿼리 정렬 컬럼 변경

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/cmm/cmm4000/cmm4000/cmm4000.jsp
=> chore : 불필요한 코드 제거 및 정리

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/top/header.jsp
=> chore : 헤더 타이틀 변경

luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/adm/adm2000/adm2000/adm2000_SQL_cubrid.xml, luna-agile/src/main/resources/egovframework/sqlmap/oslops/cubrid/adm/adm7000/adm7000/adm7000_SQL_cubrid.xml
=> chore : 주석 수정 및 제거

luna-agile/src/main/webapp/WEB-INF/jsp/oslops/cmm/cmm4000/cmm4000/cmm4000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/oslops/mainPopup.jsp
=> feat : 메인팝업 추가 및 최초 팝업 생성

luna-agile/src/main/webapp/WEB-INF/config/egovframework/springmvc/dispatcher-servlet.xml
feat : 메인팝업 호출 URL을 허용 URL에 추가
=> feat : 메인팝업 호출 URL을 허용 URL에 추가

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm2000/stm2100/stm2100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2102.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2103.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2104.jsp
* 기능 추가 : 시스템 게시판 관리 추가
* 게시판이 추가되면 게시판을 관리 할 수 있는 기능 필요
=> feat : 시스템 게시판 관리 추가

luna-agile/src/main/webapp/js/osl/osl-core.js
=> feat : core 공통 기능 추가, 오류 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp
=> feat : 사용자 요구사항 요청 변경

luna-agile/src/main/webapp/js/osl/osl-lang.js
=> style : 언어설정 문구 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp
=> chore : 파일 첨부 재업로드 막음

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2102.jsp
chore : 아이콘 변경 및 사용자 아이콘 클릭 시 해당 사용자 정보 팝업창 재연결
=> chore : 아이콘 변경 및 사용자 아이콘 클릭 시 해당 사용자 정보 팝업창 재연결

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp
style : 게시판 옵션에 따라 게시글 작성 화면 컬럼 변경
=> style : 게시판 옵션에 따라 게시글 작성 화면 컬럼 변경

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1004.jsp
chore : 기존의 bad.jsp의 request paramMap 항목 변경(개별 data -> list)에 따라 추가 변경
=> chore : 기존의 bad.jsp의 request paramMap 항목 변경(개별 data -> list)에 따라 추가 변경

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req4000/req4100/service/Req4100Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req4000/req4100/service/impl/Req4100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req4000/req4100/service/impl/Req4100ServiceImpl.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1000/prj1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/req/req4000/req4100/req4100_SQL_Oracle.xml
=> fix : 프로젝트 생성관리 - 차트 일부 작성

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1004.jsp
=> feat : css 적용 및 프로세스 세팅창 작성

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> chore: 문구 수정 및 언어팩 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp
feat: form vaildate 로직 변경 및 적용
prj1000, req1001
=> feat: form vaildate 로직 변경 및 적용

luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> style: 언어팩 추가 및 수정, 스타일 변경

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/top.jsp
=> feat: top 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/Prj1000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1000/prj1000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp
=> fix : validate 오류 수정

luna-agile/src/main/webapp/js/osl/osl-core.js
feat : 사용자 이미지 출력 시 custom 기능 추가
=> feat : 사용자 이미지 출력 시 custom 기능 추가

luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/common/modalPopup.js
=> feat : modal size full screen 추가

luna-agile/src/main/webapp/js/common/modalPopup.js
=> fix : modal popup 오류 수정

luna-agile/src/main/webapp/js/osl/osl-lang.js
=> chore : lang 문구 추가

luna-agile/src/main/webapp/css/style.osl.css
=> style : 시스템게시판 관리 style 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp
=> chore : 시스템 게시판 관리 언어설정 적용

luna-agile/src/main/webapp/css/style.osl.css
=> style : 시스템 게시판 관리 스타일변경

luna-agile/src/main/java/kr/opensoftlab/lunaops/bad/bad1000/bad1000/service/impl/Bad1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/bad/bad1000/bad1000/web/Bad1000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1000/bad1000_SQL_Oracle.xml
fix : 게시판 공지 수정 업데이트 쿼리 수정
삭제 글 복원시 파일 중복 업로드 error 해결
=> fix : 게시판 공지 수정 업데이트 쿼리 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1005.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2103.jsp
fix : 상세조회 화면에서 글 삭제 시 error 해결 
validate 체크 오류 수정
=> fix : 상세조회 화면에서 글 삭제 시 error 해결

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1000/prj1000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp
feat : sql 수정에 따라 연관된 프로젝트 설정 및 사용자 요구사항 관리 수정
=> feat : sql 수정에 따라 연관된 프로젝트 설정 및 사용자 요구사항 관리 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/Prj1000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1000/prj1000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp
feat : modal 수정에 따른 프로젝트 설정 변경, sql 수정에 따른 MVC 수정
=> feat : modal 수정에 따른 프로젝트 설정 변경, sql 수정에 따른 MVC 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1005.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dsh/dsh2000/dsh2000/dsh2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4105.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4600/req4600.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js
style : 시스템 게시판 언어팩 추가, 적용 css수정
=> style : 시스템 게시판 언어팩 추가, 적용 css수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/bad/bad1000/bad1000/service/impl/Bad1000ServiceImpl.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1000/bad1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1100/bad1100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1200/bad1200_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2103.jsp
feat : 시스템 게시판 태그 검색추가, 사용자 댓글 검색 추가
=> feat : 시스템 게시판 태그 검색추가, 사용자 댓글 검색 추가

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1000/bad1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1100/bad1100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1200/bad1200_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1005.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bottom/footer.jsp
=> fix : 시스템관리 쿼리수정, 업데이트 버그수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/bad/bad1000/bad1000/web/Bad1000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/js/osl/osl-core.js
fix : 시스템 게시판 : 태그 검색 수정
feat : searchKeyEvt 매개변수 추가
=> 시스템 게시판 태그 검색 수정, 공통 searchKeyEvt 매개변수 추가

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm2000/stm2100/stm2100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
fix : 시스템 게시판 - 게시판 옵션 수정 페이지 변경 및 lang 추가
=> fix : 시스템 게시판 - 게시판 옵션 수정 페이지 변경 및 lang 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm2000/stm2100/web/Stm2100Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2102.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
refactor : 시스템 게시판 : stm2102 제거 , stm2103 -> stm2102 변경
=> refactor : 시스템 게시판 : stm2102 제거 , stm2103 -> stm2102 변경

luna-agile/src/main/webapp/js/osl/osl-core.js
feat : searchKeyCode -1인경우 모든 키에 반응
13 = enter키인경우 기본 검색 동작 중지
=> feat : 공통 core 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3100/service/Prj3100Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3100.jsp
=> style : 산출물 양식관리 퍼블리싱

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp
style : 시스템게시판 옵션/첨부파일 사용과 태그 사용 위치 변경, 라벨 공백 추가
=> style : 시스템게시판 옵션/첨부파일 사용과 태그 사용 위치 변경, 라벨 공백 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/cmm/cmm4000/cmm4000/service/impl/Cmm4000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/cmm/cmm4000/cmm4000/web/Cmm4000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/com/vo/LoginVO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm3000/stm3000/web/Stm3000Controller.java, luna-agile/src/main/resources/egovframework/egovProps/globals.properties, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/cmm/cmm4000/cmm4000/cmm4000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bottom/footer.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/cmm/cmm4000/cmm4000/cmm4000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm3000/stm3000/stm3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/header.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/login/login.js
feat : 로그인 ID 대상 기능 추가 (email, usrId)
fix : drag&Drop 오류 수정
=> 로그인 ID 대상 기능 추가 (email, usrId)

luna-agile/src/main/webapp/js/osl/osl-core.js
=> feat : row선택시 체크박스 선택되는 로직 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp
feat : 게시판 데이터 테이블 row 선택 시 체크박스 체크되도록 추가
=> feat : 게시판 데이터 테이블 row 선택 시 체크박스 체크되도록 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp
=> style : 첨부파일 div 영역 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1005.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/css/style.osl.css
style : 게시판관련 내부 style 태그 및 css 수정
=> style : 게시판관련 내부 style 태그 및 css 수정

luna-agile/pom.xml, luna-agile/src/main/webapp/WEB-INF/web.xml
Merge development branch source code master branch
=> Merge development branch source code master branch

luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/login/login.js
fix : 로그인 ID 대상 기능 추가 (email, usrId)
=> fix : 로그인 ID 대상 기능 추가 (email, usrId)

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/css/style.osl.css
fix : 게시판 img 최대 가로사이즈 100% css로 이동 및 class추가
게시판관련 내부 style 태그 및 css 수정
=> fix : 게시판 img 최대 가로사이즈 100% css로 이동 및 class추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm6000/stm6000/web/Stm6000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm6000/stm6000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm6000/stm6001.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 조직관리 언어적용, 조직 수정 url 변경
stm6000 추가
=> feat : 조직관리 언어적용, 조직 수정 url 변경

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1001.jsp
feat: datatable 카드형 UI에서 체크박스 자동으로 제어 세팅되는 로직 추가
=> feat: datatable 카드형 UI에서 체크박스 자동으로 제어 세팅되는 로직 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9000/service/Stm9000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9000/service/impl/Stm9000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9000/service/impl/Stm9000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9000/web/Stm9000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm9000/stm9000/stm9000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9002.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
- 파일 : Stm9000DAO.java , Stm9000ServiceImpl.java , Stm9000Service.java ,
Stm9000Controller.java , stm9000_SQL_Oracle.xml , osl-lang.js ,
stm9000.jsp, stm9001.jsp , stm9002.jsp
=> feat : Jenkins 등록관리 개발(진행중, 중간커밋)

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req5000/req5000/service/impl/Req5000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req6000/req6000/service/impl/Req6000ServiceImpl.java
prj1000ServiceImple, prj1000Controller, req5000ServiceImpl,
req6000ServiceImpl과 연결되는 DAO, Service 폼만 작성(내용 없음)
=> chore: req4100 요구사항 관리

luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req4000/req4100/web/Req4100Controller.java
feat: req4100 요구사항 관리 컨트롤러 작성 및 추가
=> feat: req4100 요구사항 관리 컨트롤러 작성 및 추가

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm3000/stm3000/stm3000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2102.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2104.jsp, luna-agile/src/main/webapp/css/style.osl.css
- placeholder 주입
- modal footer button 아이콘 추가
=> feat : stm2100, bad1000 시스템 게시판 관리

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1005.jsp, luna-agile/src/main/webapp/js/osl/osl-core.js
=> feat : 프로젝트 상세보기 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp
=> feat : 게시글 등록일 agoTimeStr 적용

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1000/spr1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1000/spr1002.jsp
style : css 수정 및 적용
- prj1000, prj1001, prj1002, prj1004, req1001, spr1000, spr1002.jsp
=> style : css 수정 및 적용

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2100/spr2100.jsp
=> chore : 컬럼명 변경

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3100.jsp, luna-agile/src/main/webapp/css/style.osl.css
style : 첨부파일 고정 리스트 형태 스타일 추가
prj3000, prj3100
=> style : 첨부파일 고정 리스트 형태 스타일 추가

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2000/spr2000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2100/spr2100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2002.jsp, luna-agile/src/main/webapp/css/style.osl.css
feat : 스프린트 회의록 등록, 수정, 상세 작성 및 스타일 수정
=> feat : 스프린트 회의록 등록, 수정, 상세 작성 및 스타일 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr1000/spr1100/web/Spr1100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/service/Spr2000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/service/impl/Spr2000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/web/Spr2000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2100/web/Spr2100Controller.java
=> feat : 스프린트 서비스 및 컨트롤러

luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/web/Spr2000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2002.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 언어팩 적용 및 url 변경
spr2000관련
=> feat : 언어팩 적용 및 url 변경

luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr1000/spr1100/web/Spr1100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/web/Spr2000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2100/web/Spr2100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2000/spr2000_SQL_Oracle.xml, luna-agile/src/main/webapp/css/style.osl.css
fix : 스프린트 요구사항 배정, 회의록 부분 프로젝트 ID, 프로젝트 그룹 ID 체크 추가
=> fix : 스프린트 요구사항 배정, 회의록 부분 프로젝트 ID, 프로젝트 그룹 ID 체크 추가

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/dpl/dpl1000/dpl1000/dpl1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr1000/spr1100/spr1100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1100/spr1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2100/spr2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2100/spr2101.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
style : 스프린트 관리 placeholder, css 수정
fix : 배포 목록 조회 쿼리 수정
=> style : 스프린트 관리 placeholder, css 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/service/Spr2000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/service/impl/Spr2000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/web/Spr2000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/dpl/dpl1000/dpl1000/dpl1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2000/spr2000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2100/spr2100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm3000/stm3000/stm3000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1100/spr1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2002.jsp
feat : 회의록 컬럼 명 변경
fix : 중복 sql 제거, 회의 참여자에 사용자 사용유무 체크 추가
=> 회의록 컬럼 명 변경, 회의 참여자에 사용자 사용유무 체크 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1000/service/Dpl1000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1000/service/impl/Dpl1000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1000/service/impl/Dpl1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1000/web/Dpl1000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1100/service/Dpl1100Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1100/service/impl/Dpl1100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1100/service/impl/Dpl1100ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1100/web/Dpl1100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/dpl/dpl1000/dpl1000/dpl1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/dpl/dpl1000/dpl1100/dpl1100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/req/req4000/req4100/req4100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr1000/spr1100/spr1100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2000/spr2000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl1000/dpl1100/dpl1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1100/spr1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/css/style.osl.css
feat : 스프린트 요구사항 배정 관리, 회의록 검색 추가, select2 검색 조건 추가,
배포계획 요구사항 배정 추가
=> feat : 스프린트 요구사항 배정 관리, 회의록 검색 추가, select2 검색 조건 추가,

luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9000/web/Stm9000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9100/service/impl/Stm9100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9100/service/impl/Stm9100ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9100/web/Stm9100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm9000/stm9100/stm9100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9000/stm9000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9000/stm9002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9100/stm9100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9100/stm9101.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> feat : jenkins 상세보기 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/adm/adm5000/adm5000/service/Adm5000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/adm/adm5000/adm5000/service/impl/Adm5000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/adm/adm5000/adm5000/service/impl/Adm5000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/adm/adm5000/adm5000/web/Adm5000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj5000/prj5000/service/Prj5000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj5000/prj5000/service/impl/Prj5000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj5000/prj5000/service/impl/Prj5000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj5000/prj5000/web/Prj5000Controller.java, luna-agile/src/main/resources/egovframework/egovProps/globals.properties, luna-agile/src/main/resources/egovframework/sqlmap/config/lunaops/oracle/sql-map-config-oracle-adm5000.xml, luna-agile/src/main/resources/egovframework/sqlmap/config/lunaops/oracle/sql-map-config-oracle-prj5000.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/adm/adm5000/adm5000/adm5000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj5000/prj5000/prj5000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1200/prj1201.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj5000/prj5000/prj5000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj5000/prj5000/prj5001.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 프로젝트 일정 관리 추가, 휴일 관리 추가
=> feat : 프로젝트 일정 관리 추가, 휴일 관리 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/cmm/cmm10000/cmm16000/cmm16001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/cmm/cmm10000/cmm16000/cmm16002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/mis/mis1000/mis1000/mis1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4102.jsp, luna-agile/src/main/webapp/css/style.osl.css
style : media 쿼리 정리, 여백관련 불필요한 css 제거
=> style : media 쿼리 정리, 여백관련 불필요한 css 제거

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> chore : 시스템 게시판 관리 언어팩 적용

luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9300/service/Stm9300Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9300/service/impl/Stm9300DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9300/service/impl/Stm9300ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm9000/stm9300/web/Stm9300Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/config/lunaops/oracle/sql-map-config-oracle-stm9000.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/dpl/dpl1000/dpl1000/dpl1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm9000/stm9300/stm9300_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9300/stm9300.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> feat : jenkins 저장소 전체현황 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req1000/req1000/service/impl/Req1000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req1000/req1000/service/impl/Req1000ServiceImpl.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/req/req1000/req1000/req1000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 요구사항 잠금 기능 추가(요구사항 요청 관리)
=> feat : 요구사항 잠금 기능 추가(요구사항 요청 관리)

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl1000/dpl1000/dpl1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1000/prj1005.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1000/spr1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1000/spr1003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1000/spr1004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr1000/spr1000/spr1005.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> fix : 스프린트, 프로젝트 오류 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/bad/bad1000/bad1000/web/Bad1000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/bad/bad1000/bad1100/web/Bad1100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req4000/req4100/web/Req4100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr1000/spr1100/web/Spr1100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2000/web/Spr2000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/spr/spr2000/spr2100/web/Spr2100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm2000/stm2100/service/impl/Stm2100ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm2000/stm2100/web/Stm2100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1000/bad1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/bad/bad1000/bad1100/bad1100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2000/spr2000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2100/spr2100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm2000/stm2100/stm2100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bad/bad1000/bad1000/bad1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp
feat : datatable sort 적용, 카드형 UI 체크박스 연결
refactor : pageMap->metaMap으로 변수명 변경
=> feat : datatable sort 적용, 카드형 UI 체크박스 연결

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl1000/dpl1000/dpl1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl1000/dpl1000/dpl1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl1000/dpl1000/dpl1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl3000/dpl3000/dpl3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl3000/dpl3000/dpl3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl3000/dpl3000/dpl3002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/css/style.osl.css
feat : 배포계획 실행 완료 퍼블리싱 완료, 배포계획 생성관리(반응형 미적용) 퍼블리싱 중간 커밋, 데이터 테이블 검색 영역
=> feat : 배포계획 실행 완료 퍼블리싱 완료, 배포계획 생성관리(반응형 미적용) 퍼블리싱 중간 커밋, 데이터 테이블 검색 영역

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4104.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2100/spr2101.jsp
fix : 요구사항 등록, 스프린트 회의록 등록, 스프린트 회고록 등록 팝업의 element에 autocomplete="new-password", autocomplete="off" 적용
=> autocomplete="new-password", autocomplete="off" 적용

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/Prj1000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/service/impl/Prj1000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1100/prj1100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bottom/footer.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js, luna-agile/src/main/webapp/plugins/flowchart/jquery.flowchart.css, luna-agile/src/main/webapp/plugins/flowchart/jquery.flowchart.js
feat : 프로세스 관리 화면 추가, flow-chart 수정
=> feat : 프로세스 관리 화면 추가, flow-chart 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req3000/req3000/web/Req3000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/req/req3000/req3000/req3000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3002.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 그룹 요구사항 관리 - 등록&수정&삭제 추가
chore : 그룹 요구사항 관리, 산출물 관리 언어팩 추가
=> feat : 그룹 요구사항 관리 - 등록&수정&삭제 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/Prj3000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/impl/Prj3000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/impl/Prj3000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/web/Prj3000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3200/service/Prj3200Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3200/service/impl/Prj3200DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3200/service/impl/Prj3200ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3200/web/Prj3200Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/config/lunaops/oracle/sql-map-config-oracle-prj3200.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj3000/prj3000/prj3000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj3000/prj3200/prj3200_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3200/prj3200.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
=> feat : 산출물 양식 관리, 산출물 연결 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/req/req3000/req3000/web/Req3000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4101.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 그룹 요구사항 관리 카드 UI dropdown 메뉴 추가
=> feat : 그룹 요구사항 관리 카드 UI dropdown 메뉴 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/arm/arm1000/arm1000/web/Arm1000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/top.jsp, luna-agile/src/main/webapp/js/osl/osl-core.js, luna-agile/src/main/webapp/js/osl/osl-lang.js
refactor : 메시지 관리 패키지 변경
style : datatable row minHeight 추가
chore : 그룹 요구사항 관련 언어팩 추가
=> refactor : 메시지 관리 패키지 변경

luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/arm/arm1000/arm1000/arm1000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4101.jsp
fix : 메시지 목록 출력 order by 수정
feat : 요청자 이름 input 엔터 시 검색 팝업 호출 추가
=> fix : 메시지 목록 출력 order by 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/arm/arm1000/arm1000/web/Arm1000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1001.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js
chore : 덮어써진 내용 재커밋, cmm16000관련 arm1000 변경, 언어팩 변경
=> chore : 덮어써진 내용 재커밋, cmm16000관련 arm1000 변경, 언어팩 변경

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/top.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js
style : 메시지 팝업창 수정
chore : CSS 소스 정리, 언어팩 병합
=> style : 메시지 팝업창 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1000.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-core.js
feat : 데이터 테이블 select에 기간 추가
style : 반응형 수정, 뱃지 스타일 추가 및 기존 뱃지 수정
=> feat : 데이터 테이블 select에 기간 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3001.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-core.js
style : 그룹 요구사항 관리, 그룹 요구사항 등록&수정 팝업 레이아웃 수정
=> style : 그룹 요구사항 관리, 그룹 요구사항 등록&수정 팝업 레이아웃 수정

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/cmm/cmm1000/cmm1200/cmm1200.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj2000/prj2000/prj2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj5000/prj5000/prj5000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req1000/req1000/req1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req4000/req4100/req4102.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2000/stm2000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2200/stm2200.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm6000/stm6000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm9000/stm9200/stm9200.jsp
style : kt-portlet__head-group 이중 구조 제거
=> style : kt-portlet__head-group 이중 구조 제거

luna-agile/src/main/webapp/css/style.osl.css
=> style: 산출물 관련 css 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/cmm/cmm9000/cmm9000/web/Cmm9000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/usr/usr1000/usr1000/service/Usr1000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/usr/usr1000/usr1100/service/Usr1100Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/usr/usr1000/usr1100/service/impl/Usr1100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/usr/usr1000/usr1100/service/impl/Usr1100ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/usr/usr1000/usr1100/web/Usr1100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/config/lunaops/oracle/sql-map-config-oracle-usr1100.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/req/req1000/req1000/req1000_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/usr/usr1000/usr1100/usr1100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/usr/usr1000/usr1000/usr1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/usr/usr1000/usr1000/usr1003.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-lang.js
feat : 단축키 기능 추가, 그룹요구사항 관리 UI 수정
=> feat : 단축키 기능 추가, 그룹요구사항 관리 UI 수정

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3100/web/Prj3100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/spr/spr2000/spr2000/spr2000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/req/req3000/req3000/req3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/spr/spr2000/spr2000/spr2001.jsp
chore : 쿼리 컬럼명 변경, 오타 수정
feat : 산출물 관리 양식 다운로드 팝업 추가
=> chore : 쿼리 컬럼명 변경, 오타 수정

luna-agile/src/main/webapp/js/common/modalPopup.js, luna-agile/src/main/webapp/js/osl/osl-lang.js
fix : modal touchspin 오류 수정
chore : 산출물 관리 언어팩 수정
=> fix : modal touchspin 오류 수정

luna-agile/pom.xml, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm2000/stm2100/web/Stm2100Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/service/Stm8000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/service/impl/Stm8000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/service/impl/Stm8000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/web/Stm8000Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/config/lunaops/oracle/sql-map-config-oracle-stm8000.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm2000/stm2100/stm2100_SQL_Oracle.xml, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/stm/stm8000/stm8000/stm8000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bottom/footer.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/dpl/dpl1000/dpl1100/dpl1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2101.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8002.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8003.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8004.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8005.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/plugins/diff/diff_match_patch_uncompressed.js
feat : 소스 저장소 등록 관리 추가
pom.xml의 jgit 테스트용으로 삽입
=> feat : 소스 저장소 등록 관리 추가

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/bottom/footer.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1100/prj1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1100/prj1102.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/header.jsp, luna-agile/src/main/webapp/css/style.osl.css, luna-agile/src/main/webapp/js/osl/osl-core.js, luna-agile/src/main/webapp/plugins/flowchart/jquery.flowchart.js
=> feat : 프로세스 설정, 소스 코드 병합

luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/service/Stm8000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/service/impl/Stm8000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/service/impl/Stm8000ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/stm/stm8000/stm8000/web/Stm8000Controller.java, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm8000/stm8000/stm8000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/top.jsp
feat :  소스 저장소 등로관리 - 저장소 연결확인 추가
fix : message idkey 삽입
=> feat :  소스 저장소 등로관리 - 저장소 연결확인 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/Prj3000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/web/Prj3000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3100/service/impl/Prj3100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3100/service/impl/Prj3100ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3100/web/Prj3100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/cubrid/prj/prj3000/prj3100/prj3100_SQL_cubrid.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3000/prj3001.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3100.jsp
fix : 산출물 파일 변경 정보 추가 및 결재 미확정 파일 전체 다운로드시 다운로드 안되게 변경
=> fix : 산출물 파일 변경 정보 추가 및 결재 미확정 파일 전체 다운로드시 다운로드 안되게 변경

luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/arm/arm1000/arm1000/arm1000.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/stm/stm2000/stm2100/stm2100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/top/header.jsp, luna-agile/src/main/webapp/js/osl/osl-chart.js, luna-agile/src/main/webapp/js/osl/osl-core.js
feat : 공통 chart 개발 진행
fix : 보낸 메시지 bold 처리 해제
=> feat : 공통 chart 개발 진행

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/service/Prj1100Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/service/impl/Prj1100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/service/impl/Prj1100ServiceImpl.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/web/Prj1100Controller.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1100/prj1100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1100/prj1100.jsp, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1100/prj1102.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js, luna-agile/src/main/webapp/plugins/flowchart/jquery.flowchart.js
=> feat : 프로세스 단계 생성 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1000/web/Prj1000Controller.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/service/Prj1100Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/service/impl/Prj1100DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj1000/prj1100/service/impl/Prj1100ServiceImpl.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj1000/prj1100/prj1100_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj1000/prj1100/prj1100.jsp, luna-agile/src/main/webapp/js/osl/osl-lang.js, luna-agile/src/main/webapp/plugins/flowchart/jquery.flowchart.js
feat : 프로세스 등록, 수정, 삭제 추가
프로세스 단계 추가, 수정, 삭제 추가
=> feat : 프로세스 등록, 수정, 삭제 추가

luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/Prj3000Service.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/impl/Prj3000DAO.java, luna-agile/src/main/java/kr/opensoftlab/lunaops/prj/prj3000/prj3000/service/impl/Prj3000ServiceImpl.java, luna-agile/src/main/resources/egovframework/sqlmap/lunaops/oracle/prj/prj3000/prj3000/prj3000_SQL_Oracle.xml, luna-agile/src/main/webapp/WEB-INF/jsp/lunaops/prj/prj3000/prj3100/prj3100.jsp
=> fix : 프로젝트 생성관리에서 사용중인 메서드 복구

luna-agile/src/main/java/kr/opensoftlab/lunaops/dpl/dpl1000/dpl1100/web/Dpl1100Controller.java
=> chore : 불필요 import  제거
